[package]
name = "fuiz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-web = "4.3.1"
actix-ws = "0.2.5"
async-trait = "0.1.72"
atomig = { version = "0.4.0", features = ["derive"] }
chrono = { version = "0.4.26", features = ["serde"] }
dashmap = "5.5.0"
derive-where = "1.2.1"
diesel = { version = "2.1.0", features = ["postgres", "r2d2", "chrono"] }
dotenvy = "0.15.7"
enum-map = "2.6.1"
erased-serde = "0.3.28"
fastrand = "2.0.0"
futures-util = "0.3.28"
itertools = "0.11.0"
kinded = "0.3.0"
log = "0.4.19"
mockall = "0.11.4"
pretty_env_logger = "0.5.0"
r2d2 = "0.8.10"
serde = { version = "1.0.173", features = ["derive"] }
serde_json = "1.0.103"
serde_with = { version = "3.1.0", features = ["chrono"] }
thiserror = "1.0.44"
uuid = { version = "1.4.1", features = ["v4", "serde"] }
