[package]
name = "fuiz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
actix-ws = "0.2.5"
chrono = { version = "0.4.26", features = ["serde"] }
dashmap = "5.5.0"
diesel = { version = "2.1.0", features = ["postgres", "r2d2", "chrono"] }
dotenvy = "0.15.7"
fastrand = "2.0.0"
futures-util = "0.3.28"
r2d2 = "0.8.10"
serde = { version = "1.0.173", features = ["derive"] }
serde_json = "1.0.103"
serde_with = { version = "3.1.0", features = ["chrono"] }
uuid = "1.4.1"
